#!/usr/bin/env sh
# ============================================================
# Pulse — one-command installer.
#
#   curl -fsSL https://raw.githubusercontent.com/roman0309/pulse/main/deploy/install.sh | sh
#
# Private (Tailscale) install — no domain, no public ports, auto HTTPS:
#   curl -fsSL .../deploy/install.sh | TS_AUTHKEY=tskey-auth-xxxx sh
#
# Downloads the standalone compose file, generates secrets into .env, and
# starts Pulse. Requires Docker with the Compose plugin.
# ============================================================
set -eu

REPO_RAW="https://raw.githubusercontent.com/roman0309/pulse/main/deploy"
DIR="${PULSE_DIR:-pulse}"
TS_HOSTNAME="${TS_HOSTNAME:-pulse}"

say() { printf '\033[36m›\033[0m %s\n' "$1"; }
err() { printf '\033[31m✗\033[0m %s\n' "$1" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || err "Docker is required. See https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || err "The Docker Compose plugin is required (docker compose)."

gen() {
  if command -v openssl >/dev/null 2>&1; then openssl rand -hex 32
  else head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'; fi
}

say "Creating ./$DIR"
mkdir -p "$DIR"
cd "$DIR"

say "Downloading compose file"
curl -fsSL "$REPO_RAW/docker-compose.yml" -o docker-compose.yml

USE_TS=0
if [ -n "${TS_AUTHKEY:-}" ]; then
  USE_TS=1
  say "Tailscale mode enabled"
  mkdir -p tailscale
  curl -fsSL "$REPO_RAW/tailscale/serve.json" -o tailscale/serve.json
fi

if [ ! -f .env ]; then
  say "Generating secrets into .env"
  {
    echo "# Generated by install.sh — keep this file secret."
    echo "POSTGRES_PASSWORD=$(gen)"
    echo "CLICKHOUSE_PASSWORD=$(gen)"
    echo "JWT_SECRET=$(gen)"
    echo "JWT_REFRESH_SECRET=$(gen)"
    echo "HTTP_PORT=80"
    if [ "$USE_TS" -eq 1 ]; then
      echo "TS_AUTHKEY=$TS_AUTHKEY"
      echo "TS_HOSTNAME=$TS_HOSTNAME"
      # PUBLIC_INGEST_URL / CORS_ORIGINS are filled in after Tailscale connects.
      echo "PUBLIC_INGEST_URL="
      echo "CORS_ORIGINS="
    else
      echo "PUBLIC_INGEST_URL=http://localhost:8080"
      echo "CORS_ORIGINS=http://localhost"
    fi
  } > .env
else
  say "Keeping existing .env"
fi

if [ "$USE_TS" -eq 1 ]; then
  say "Starting Pulse on your Tailscale network"
  docker compose --profile tailscale pull
  docker compose --profile tailscale up -d

  say "Waiting for Tailscale to connect…"
  suffix=""
  i=0
  while [ "$i" -lt 30 ]; do
    suffix=$(docker compose --profile tailscale exec -T tailscale tailscale status --json 2>/dev/null \
      | grep -o '"MagicDNSSuffix": *"[^"]*"' | head -n1 | cut -d'"' -f4 || true)
    [ -n "$suffix" ] && break
    i=$((i + 1)); sleep 2
  done

  if [ -n "$suffix" ]; then
    URL="https://$TS_HOSTNAME.$suffix"
    say "Detected Tailscale URL: $URL"
    sed "s#^PUBLIC_INGEST_URL=.*#PUBLIC_INGEST_URL=$URL#; s#^CORS_ORIGINS=.*#CORS_ORIGINS=$URL#" .env > .env.tmp && mv .env.tmp .env
    docker compose --profile tailscale up -d
    printf '\n\033[32m✓ Pulse is private on your tailnet.\033[0m\n'
    printf '  URL:   %s   (UI + agent ingest, auto HTTPS)\n' "$URL"
    printf '  Next:  open %s and register the first user.\n\n' "$URL"
  else
    printf '\n\033[33m! Tailscale did not report a name yet.\033[0m Check `docker compose --profile tailscale logs tailscale`,\n'
    printf '  then set PUBLIC_INGEST_URL=https://%s.<your-tailnet>.ts.net in .env and rerun `docker compose --profile tailscale up -d`.\n\n' "$TS_HOSTNAME"
  fi
else
  say "Pulling images and starting Pulse"
  docker compose pull
  docker compose up -d
  printf '\n\033[32m✓ Pulse is starting.\033[0m\n'
  printf '  UI:    http://localhost\n'
  printf '  API:   http://localhost:8080\n'
  printf '  Next:  open the UI and register the first user (becomes owner).\n\n'
fi

printf '  Manage: cd %s && docker compose [logs -f|down|pull]\n\n' "$DIR"
