#!/usr/bin/env sh
# ============================================================
# Pulse — one-command installer.
#
#   curl -fsSL https://raw.githubusercontent.com/roman0309/pulse/main/deploy/install.sh | sh
#
# Downloads the standalone compose file, generates secrets into .env, and
# starts Pulse. Requires Docker with the Compose plugin.
# ============================================================
set -eu

REPO_RAW="https://raw.githubusercontent.com/roman0309/pulse/main/deploy"
DIR="${PULSE_DIR:-pulse}"

say() { printf '\033[36m›\033[0m %s\n' "$1"; }
err() { printf '\033[31m✗\033[0m %s\n' "$1" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || err "Docker is required. Install it from https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || err "The Docker Compose plugin is required (docker compose)."

# Generate a random secret (openssl if available, else /dev/urandom).
gen() {
  if command -v openssl >/dev/null 2>&1; then openssl rand -hex 32
  else head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'; fi
}

say "Creating ./$DIR"
mkdir -p "$DIR"
cd "$DIR"

say "Downloading compose file"
curl -fsSL "$REPO_RAW/docker-compose.yml" -o docker-compose.yml

if [ ! -f .env ]; then
  say "Generating secrets into .env"
  cat > .env <<EOF
# Generated by install.sh — keep this file secret.
POSTGRES_PASSWORD=$(gen)
CLICKHOUSE_PASSWORD=$(gen)
JWT_SECRET=$(gen)
JWT_REFRESH_SECRET=$(gen)

# Public URL agents push telemetry to. Change to your domain in production,
# e.g. https://pulse.example.com  (and put a TLS reverse proxy in front).
PUBLIC_INGEST_URL=http://localhost:8080
CORS_ORIGINS=http://localhost
HTTP_PORT=80
EOF
else
  say "Keeping existing .env"
fi

say "Pulling images and starting Pulse"
docker compose pull
docker compose up -d

printf '\n\033[32m✓ Pulse is starting.\033[0m\n'
printf '  UI:        http://localhost\n'
printf '  API:       http://localhost:8080\n'
printf '  Next:      open the UI and register the first user (becomes owner).\n'
printf '  Manage:    cd %s && docker compose [logs -f|down|pull]\n\n' "$DIR"
